spring:
  application:
    name: jvolt
  datasource:
    url: jdbc:postgresql://localhost:5433/jwt_security
    username: ho
    password: rkfdk1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  mail:
    auth-code-expiration-millis: 1800000
  thymeleaf:
    prefix=: classpath:/templates/
    suffix=: .html
    cache=: false  # 개발 환경에서 템플릿 캐시 비활성화
